Добавлен бейджик codecov
sergio-fry/history pull request #43
Opened 2024-05-24 12:12 UTC by sas2job

2024-05-24 14:39 UTC, sas2job commented
> А как будет обноваляться этот показатель?

Каждый раз после запуска тестов.

2024-05-24 15:39 UTC, sergio-fry commented
а что, если разработчик забудет запушить правки?

2024-05-24 17:27 UTC, sas2job commented
Убрал гем который выводит локальную плашку.

2024-05-27 09:34 UTC, sergio-fry commented on features/support/env.rb
> +  # options.binary = "/usr/bin/firefox"
а вот это зачем?

2024-05-28 07:24 UTC, sergio-fry requested changes
есть вопрос

2024-05-28 11:02 UTC, sas2job commented on features/support/env.rb
> +  # options.binary = "/usr/bin/firefox"
Убрал

2024-05-28 11:10 UTC, merged